name: Flutter Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Flutter (with newer Dart SDK)
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'  # Contains Dart 3.7.5
        channel: 'stable'
    
    - name: Verify Dart version
      run: dart --version  # Should show 3.7.5
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
